### ISSUE TITLE
Please check for local addresses

### ISSUE THREAD

**Issue by busterix76** [hackinghippo/log4shell_ioc_ips#1]
192.168.99.116
172.17.0.3
172.18.10.187
172.20.10.10
172.31.18.187
172.31.41.177
172.31.53.193

**Comment by busterix76** [comment]
Also OpenDNS:
146.112.61.110

**Comment by hackinghippo** [comment]
I added the script.sh in the repo so maybe someone will work on it.
I will try my best to fix the regex but currently I have no time because log4j

**Comment by hackinghippo** [comment]
fixed in 5a520f1
