### ISSUE TITLE
Feed suddenly empty?

### ISSUE THREAD

**Issue by brycied00d** [hackinghippo/log4shell_ioc_ips#3]
Heads up, b9a80177034fd5804b508c1e7de766d693245e60 has deleted all IPs

**Comment by brycied00d** [comment]
85c01813b2407495d44645acdb6efd08c9483798 seems to have resolved this.

**Comment by hackinghippo** [comment]
fixed I worked at the master branch ... tried a new regex to exclude local ip adress ranges
